os: linux
compiler: gcc
language: cpp
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.9
            - libfuse-dev
            - fuse
            - attr
before_install:
    - pip install --user cpp-coveralls
    - sudo chmod 666 /dev/fuse
script:
    - make test CXX="g++-4.9" CFLAGS="-O0 --coverage" LDFLAGS="-Wl,-Bstatic -lfuse -Wl,-Bdynamic -ldl"
    - find -type f
after_success:
    - coveralls --verbose --gcov gcov-4.9 --gcov-options '\-lp'
    - find -type f
