os: linux
compiler: gcc
language: cpp
sudo: required
dist: trusty
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.9
            - libfuse-dev
            - fuse
            - attr
            - lcov
before_install:
    - gem install coveralls-lcov
    - sudo chmod 666 /dev/fuse
script:
    - make test CXX="g++-4.9" CFLAGS="-O0 --coverage" LDFLAGS="-Wl,-Bstatic -lfuse -Wl,-Bdynamic -ldl"
after_success:
    - lcov --compat-libtool --directory . --capture --output-file coverage.info
    - coveralls-lcov coverage.info
