os: linux
dist: trusty
compiler: gcc
language: cpp
before_install:
- pip install --user cpp-coveralls
- sudo apt-get -qq update
- sudo apt-get install -qq -y libfuse-dev g++-4.8
script:
- make test CFLAGS="-O0 --coverage" CXX=g++-4.8
after_success:
- coveralls --gcov-options '\-lp'
